spring.application.name=messaging-service
server.port=8085
server.servlet.context-path=/messaging-service
spring.profiles.active=qa
logging.level.root=INFO
management.endpoints.web.exposure.include=health,info